# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f2ae66f5768a8fdb229b4ec13f83dc43efb8eb0ac9c0beb7c630d199fbdb540f9c17ebc023049335bfd1bcebc0f17c892d07d4d5cbd4541055a2054c0ec6638

test:
  secret_key_base: fa91949560b24c480f7b6ec50f72005578a6dfd29f5708a05eadfb68e00a38dfcbd53e126654a9b4134d1e3176ec47027fbc12d501b7ecda8e863988e586ce2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
